apiVersion: v1
kind: Secret
metadata:
  namespace: cluster-backup
  name: cloud-credentials
  labels:
    component: minio
stringData:
  cloud: |
    [default]
    aws_access_key_id = minio
    aws_secret_access_key = minio123
---
apiVersion: ark.heptio.com/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: cluster-backup
spec:
  provider: aws
  objectStorage:
    bucket: ark
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://minio.heptio-ark.svc:9000
