apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: snapshots.clustersnapshot.rywt.io
spec:
  group: clustersnapshot.rywt.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Snapshot
    plural: snapshots
  additionalPrinterColumns:
  - name: CLUSTER
    type: string
    description: Cluster ID.
    JSONPath: .spec.clusterName
  - name: TIMESTAMP
    type: string
    description: Timestamp of snapshot.
    JSONPath: .status.snapshotTimestamp
  - name: RV
    type: string
    description: Resource Version of snapshot.
    JSONPath: .status.snapshotResourceVersion
  - name: AVAILABLE_UNTIL
    type: string
    description: Retention period of snapshot.
    JSONPath: .status.availableUntil
  - name: CONTENTS
    type: integer
    description: Number of contents.
    JSONPath: .status.numberOfContents
  - name: SIZE
    type: integer
    description: Snapshot file size.
    JSONPath: .status.storedFileSize
  - name: OBJECTSTORE
    type: string
    description: Objectstore config name.
    JSONPath: .spec.objectstoreConfig
  - name: STATUS
    type: string
    description: Status of snapshot.
    JSONPath: .status.phase
  - name: AGE
    type: date
    description: Timestamp of snapshot.
    JSONPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: restores.clustersnapshot.rywt.io
spec:
  group: clustersnapshot.rywt.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Restore
    plural: restores
  additionalPrinterColumns:
  - name: CLUSTER
    type: string
    description: Cluster ID.
    JSONPath: .spec.clusterName
  - name: SNAPSHOT
    type: string
    description: Snapshot data ID used for restore.
    JSONPath: .spec.snapshotName
  - name: TIMESTAMP
    type: string
    description: Timestamp of restore.
    JSONPath: .status.restoreTimestamp
  - name: RV
    type: string
    description: Resource Version of restore.
    JSONPath: .status.restoreResourceVersion
  - name: EXCLUDED
    type: integer
    description: Number of excluded by conditions.
    JSONPath: .status.numExcluded
  - name: CREATED
    type: integer
    description: Number of created.
    JSONPath: .status.numCreated
  - name: UPDATED
    type: integer
    description: Number of updated.
    JSONPath: .status.numUpdated
  - name: EXIST
    type: integer
    description: Number of already existed.
    JSONPath: .status.numAlreadyExisted
  - name: FAILED
    type: integer
    description: Number of failed.
    JSONPath: .status.numFailed
  - name: STATUS
    type: string
    description: Status of snapshot.
    JSONPath: .status.phase
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: restorepreferences.clustersnapshot.rywt.io
spec:
  group: clustersnapshot.rywt.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: RestorePreference
    plural: restorepreferences
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: objectstoreconfigs.clustersnapshot.rywt.io
spec:
  group: clustersnapshot.rywt.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: ObjectstoreConfig
    plural: objectstoreconfigs
  additionalPrinterColumns:
  - name: REGION
    type: string
    description: Region.
    JSONPath: .spec.region
  - name: ENDPOINT
    type: string
    description: Endpoint.
    JSONPath: .spec.endpoint
  - name: CREDENTIAL
    type: string
    description: Cloud credential secret name.
    JSONPath: .spec.cloudCredentialSecret
  - name: BUCKET
    type: string
    description: Bucket name.
    JSONPath: .spec.bucket
  - name: AGE
    type: date
    description: Timestamp of snapshot.
    JSONPath: .metadata.creationTimestamp
