apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backups.clusterbackup.ssl
spec:
  group: clusterbackup.ssl
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Backup
    plural: backups
  additionalPrinterColumns:
  - name: CLUSTERNAME
    type: string
    description: Cluster ID.
    JSONPath: .spec.clusterName
  - name: TIMESTAMP
    type: string
    description: Timestamp of backup.
    JSONPath: .status.backupTimestamp
  - name: AVAILABLE_UNTIL
    type: string
    description: Retention period of backup.
    JSONPath: .status.availableUntil
  - name: CONTENTS
    type: integer
    description: Number of contents.
    JSONPath: .status.numberOfContents
  - name: SIZE
    type: integer
    description: Backup file size.
    JSONPath: .status.backupFileSize
  - name: TTL
    type: string
    description: TTL of backup.
    JSONPath: .spec.ttl
  - name: STATUS
    type: string
    description: Status of backup.
    JSONPath: .status.phase
  - name: AGE
    type: date
    description: Timestamp of backup.
    JSONPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: restores.clusterbackup.ssl
spec:
  group: clusterbackup.ssl
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Restore
    plural: restores
  additionalPrinterColumns:
  - name: CLUSTERNAME
    type: string
    description: Cluster ID.
    JSONPath: .spec.clusterName
  - name: BACKUPNAME
    type: string
    description: Backup data ID used for restore.
    JSONPath: .spec.backupName
  - name: RESTOREDATE
    type: string
    description: Timestamp of restore.
    JSONPath: .metadata.creationTimestamp
  - name: STATUS
    type: string
    description: Status of backup.
    JSONPath: .status.phase
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: restorepreferences.clusterbackup.ssl
spec:
  group: clusterbackup.ssl
  version: v1alpha1
  scope: Namespaced
  names:
    kind: RestorePreference
    plural: restorepreferences
