apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-backup-controller
  namespace: k8s-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-backup-controller
  template:
    metadata:
      labels:
        app: k8s-backup-controller
    spec:
      containers:
        - name: k8s-backup-controller
          image: [image]:[TAG]
          env:
          command:
            - /k8s-backup-controller
            - --namespace=k8s-backup
