apiVersion: clustersnapshot.rywt.io/v1alpha1
kind: Snapshot
metadata:
  name: cluster01-001
  namespace: k8s-snap
spec:
  clusterName: cluster01
  objectstoreConfig: k8s-snap-ap-northeast-1
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akND...
        server: https://cluster01.kubernetes.111.111.111.111.nip.io:6443
      name: cluster
    contexts:
    - context:
        cluster: cluster
        user: remote-user
      name: context
    current-context: context
    kind: Config
    preferences: {}
    users:
    - name: remote-user
      user:
        token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVz....
  ttl: 720h
  availableUntil: 2020-07-01T02:03:04Z
