apiVersion: v1
kind: Namespace
metadata:
  name: k8s-backup-controller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-backup-controller
  labels:
    component: k8s-backup
subjects:
  - kind: ServiceAccount
    namespace: cluster-backup
    name: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
