apiVersion: clustersnapshot.rywt.io/v1alpha1
kind: RestorePreference
metadata:
  name: exclude-kube-system
  namespace: k8s-snap
spec:
  excludeNamespaces:
    - "kube-system"
    - "kube-public"
    - "ingress-nginx"
  excludeCRDs:
    - "crd.projectcalico.org"
  excludeApiPathes:
  # prefix / prefix,contains
    - "/api/v1,bindings"
    - "/api/v1,componentstatuses"
    - "/api/v1,events"
    - "/api/v1,limitranges"
    - "/api/v1,nodes"
    - "/api/v1,resourcequotas"
    - "/apis/apiregistration.k8s.io"
    # Ignore /apis/extensions path for Apps.
    - "/apis/extensions,daemonsets"
    - "/apis/extensions,deployments"
    - "/apis/extensions,networkpolicies"
    - "/apis/extensions,podsecuritypolicies"
    - "/apis/extensions,replicasets"
    - "/apis/extensions,replicationcontrollers"
    - "/apis/scheduling.k8s.io"
    - "/apis/events.k8s.io"
    - "/apis/certificates.k8s.io"
    - "/apis/networking.k8s.io"
    - "/apis/admissionregistration.k8s.io"
    - "/apis/authentication.k8s.io"
    - "/apis/authorization.k8s.io"
    # Custom resource pathes not matched here will be restored.
    - "/apis/crd.projectcalico.org"
    # Exclude system resource.
    - "/api/v1/namespaces/default/services/kubernetes"
    - "/api/v1/namespaces/default/endpoints/kubernetes"
    - "/apis/rbac.authorization.k8s.io/v1/clusterroles/system%3A"
    - "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/system%3A"

    #######      Resources will be restored.    #########################################################################
    #   RESOURCES                                               ADDITIONAL CONDITIONS
    # - "/api/v1,configmaps"
    # - "/api/v1,endpoints"                                     # Restore endpoints not created with services.
    # - "/api/v1,namespaces"
    # - "/api/v1,persistentvolumeclaims"                        # Restore restoreNfsStorageClass PVs bounded with PVCs.
    # - "/api/v1,persistentvolumes"                             # Restore PVCs bounded to restoreNfsStorageClass PVs.
    # - "/api/v1,pods"                                          # Restore pods not owned by other apps.
    # - "/api/v1,podtemplates"
    # - "/api/v1,secrets"                                       # Restore secrets except serviceaccounts' token.
    # - "/api/v1,serviceaccounts"
    # - "/api/v1,services"
    # - "/apis/rbac.authorization.k8s.io,role"
    # - "/apis/rbac.authorization.k8s.io,rolebindings"
    # - "/apis/rbac.authorization.k8s.io,clusterrole"           # Restore clusterroles for restored namespaces' ServiceAccounts.
    # - "/apis/rbac.authorization.k8s.io,clusterrolebindings"   # Restore clusterrolebindings for restored namespaces' ServiceAccounts.
    # - "/apis/apiextensions.k8s.io,customresourcedefinitions"
    # - "/apis/apps,controllerrevisions"
    # - "/apis/apps,daemonsets"
    # - "/apis/apps,deployments"
    # - "/apis/apps,replicasets"
    # - "/apis/apps,statefulsets"
    # - "/apis/extensions,ingresses"
    # - "/apis/autoscaling,horizontalpodautoscalers"
    # - "/apis/batch,jobs"
    # - "/apis/batch,cronjobs"
    # - "/apis/storage.k8s.io,storageclasses"                   # Restore storageclasses matches restoreNfsStorageClass
    #######################################################################################################################

  restoreAppApiPathes:
  # prefix / prefix,contains
  # Apps must be restored after other resources restored.
    - "/api/v1,pods"
    - "/api/v1,replicationcontrollers"
    - "/apis/apps"
    - "/api/v1,endpoints"
    - "/api/v1,services"
    - "/apis/extensions,ingresses"
    - "/apis/autoscaling,horizontalpodautoscalers"
    - "/apis/batch,jobs"
    - "/apis/batch,cronjobs"
  restoreNfsStorageClasses:
  # prefix
    - "managed-nfs-storage"
  restoreOptions: []
    # - "overwriteExistingResources"
